services:
  database:
    image: postgres:16.0-alpine
    container_name: db
    environment:
      - POSTGRES_USER={DB_USER}
      - POSTGRES_PASSWORD={DB_PASSWORD}
      - POSTGRES_DB=doctortime
    volumes:
      - db-volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    image: doctortime:latest
    build:
      context: .
    container_name: app
    depends_on:
      - database
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/doctortime
      - SPRING_DATASOURCE_USERNAME={DB_USER}
      - SPRING_DATASOURCE_PASSWORD={DB_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8080"

volumes:
  db-volume:
